#|
 This file is a part of Trainer
 (c) 2013 TymoonNET/NexT http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.tymoonnext.colleen.mod.trainer)

(define-dictionary genki-1
  (("いま") . ("now"))
  (("えいご") . ("english"))
  (("ええ") . ("yes"))
  (("がくせい") . ("student"))
  (("~ご") . ("language"))
  (("こうこう") . ("high school"))
  (("ごご") . ("pm"))
  (("ごぜん") . ("am"))
  (("~さい") . ("years old"))
  (("~さん") . ("mr" "ms" "mr/ms"))
  (("~さい") . ("years old"))
  (("~じ") . ("o'clock" "o clock"))
  (("~じん") . ("people"))
  (("せんこう") . ("major"))
  (("せんせい") . ("teacher" "professor"))
  (("だいがく") . ("college" "university" "uni"))
  (("でんわ") . ("telephone"))
  (("ともだち") . ("friend" "friends"))
  (("なまえ") . ("name"))
  (("なん" "なに") . ("what"))
  (("にほん") . ("japan"))
  (("~ねんせい") . ("year student" "grade student"))
  (("はい") . ("yes"))
  (("はん") . ("half"))
  (("ばんごう") . ("number"))
  (("りゅうがくせい") . ("international student"))
  (("わたし") . ("I"))
  (("アメリカ") . ("amerika"))
  (("イギリス") . ("england"))
  (("オーストラリア") . ("australia"))
  (("かんこく") . ("korea"))
  (("スウエーデン") . ("sweden"))
  (("ちゅうごく") . ("china"))
  (("かがく") . ("science"))
  (("アジアけんきゅう") . ("asian studies"))
  (("けいざい") . ("economics"))
  (("こくさいかんけい") . ("international relations"))
  (("コンピューター") . ("computer"))
  (("じんるいがく") . ("anthropology"))
  (("せいじ") . ("politics"))
  (("ビジネス") . ("business"))
  (("ぶんがく") . ("literature"))
  (("れきし") . ("history"))
  (("しごと") . ("job" "work" "occupation"))
  (("いしゃ") . ("doctor"))
  (("かいしゃいん") . ("office worker"))
  (("こうこうせい") . ("high school student"))
  (("しゅふ") . ("house wife" "housewife"))
  (("だいがくいんせい") . ("graduate student"))
  (("だいがくせい") . ("college student"))
  (("べんごし") . ("lawyer"))
  (("おかあさん") . ("mother"))
  (("おとうさん") . ("father"))
  (("おねえさん") . ("older sister"))
  (("おにいさん") . ("older brother"))
  (("いもうと") . ("younger sister"))
  (("おとうと") . ("younger brother")))
