#|
 This file is a part of Trainer
 (c) 2013 TymoonNET/NexT http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.tymoonnext.colleen.mod.trainer)

(define-dictionary genki-1
  (("いま") . ("now"))
  (("えいご") . ("english"))
  (("ええ") . ("yes"))
  (("がくせい") . ("student"))
  (("~ご") . ("language"))
  (("こうこう") . ("high school"))
  (("ごご") . ("pm"))
  (("ごぜん") . ("am"))
  (("~さい") . ("years old"))
  (("~さん") . ("mr" "ms" "mr/ms"))
  (("~さい") . ("years old"))
  (("~じ") . ("o'clock" "o clock"))
  (("~じん") . ("people"))
  (("せんこう") . ("major"))
  (("せんせい") . ("teacher" "professor"))
  (("だいがく") . ("college" "university" "uni"))
  (("でんわ") . ("telephone"))
  (("ともだち") . ("friend" "friends"))
  (("なまえ") . ("name"))
  (("なん" "なに") . ("what"))
  (("にほん") . ("japan"))
  (("~ねんせい") . ("year student" "grade student"))
  (("はい") . ("yes"))
  (("はん") . ("half"))
  (("ばんごう") . ("number"))
  (("りゅうがくせい") . ("international student"))
  (("わたし") . ("I"))
  (("アメリカ") . ("amerika"))
  (("イギリス") . ("england"))
  (("オーストラリア") . ("australia"))
  (("かんこく") . ("korea"))
  (("スウエーデン") . ("sweden"))
  (("ちゅうごく") . ("china"))
  (("かがく") . ("science"))
  (("アジアけんきゅう") . ("asian studies"))
  (("けいざい") . ("economics"))
  (("こくさいかんけい") . ("international relations"))
  (("コンピューター") . ("computer"))
  (("じんるいがく") . ("anthropology"))
  (("せいじ") . ("politics"))
  (("ビジネス") . ("business"))
  (("ぶんがく") . ("literature"))
  (("れきし") . ("history"))
  (("しごと") . ("job" "work" "occupation"))
  (("いしゃ") . ("doctor"))
  (("かいしゃいん") . ("office worker"))
  (("こうこうせい") . ("high school student"))
  (("しゅふ") . ("house wife" "housewife"))
  (("だいがくいんせい") . ("graduate student"))
  (("だいがくせい") . ("college student"))
  (("べんごし") . ("lawyer"))
  (("おかあさん") . ("mother"))
  (("おとうさん") . ("father"))
  (("おねえさん") . ("older sister"))
  (("おにいさん") . ("older brother"))
  (("いもうと") . ("younger sister"))
  (("おとうと") . ("younger brother")))

(define-dictionary genki-2
  (("これ") . ("this one"))
  (("それ") . ("that one"))
  (("あれ") . ("that one" "that one over there"))
  (("どれ") . ("which one"))
  (("この") . ("this"))
  (("その") . ("that"))
  (("あの") . ("that" "that over there"))
  (("どの") . ("which"))
  (("ここ") . ("here"))
  (("そこ") . ("there"))
  (("あそこ") . ("there" "over there"))
  (("とこ") . ("where"))
  (("だれ") . ("who"))
  (("おいしい") . ("delicious"))
  (("さかな") . ("fish"))
  (("とんかつ") . ("pork cutlet" "pork"))
  (("にく") . ("meat"))
  (("メニュウ") . ("menu"))
  (("やさい") . ("vegetable"))
  (("えんぴつ") . ("pencil"))
  (("かさ") . ("umbrella"))
  (("かばん") . ("bag"))
  (("くつ") . ("shoes"))
  (("さいふ") . ("wallet"))
  (("ジーンス") . ("jeans"))
  (("じしょ") . ("dictionary"))
  (("じてんしゃ") . ("bicycle"))
  (("しんぶん") . ("newspaper"))
  (("Ｔシャツ") . ("tshirt" "t shirt"))
  (("とけい") . ("watch"))
  (("ノート") . ("notebook"))
  (("ペン") . ("pen"))
  (("ぼうし") . ("hat" "cap"))
  (("ほん") . ("book"))
  (("きっさてん") . ("cafe"))
  (("ぎんこう") . ("bank"))
  (("トイレ") . ("toilet"))
  (("としょかん") . ("library"))
  (("ゆうびんきゃく") . ("post office" "post"))
  (("アメリカ") . ("amerika"))
  (("イギリス") . ("england"))
  (("かんこく") . ("korea"))
  (("ちゅうごく") . ("china"))
  (("けいざい") . ("economics"))
  (("コンピューター") . ("computer"))
  (("ビジネス") . ("business"))
  (("れきし") . ("history"))
  (("おかあさん") . ("mother"))
  (("おとうさん") . ("father"))
  (("いくら") . ("how much" "how much does it cost" "how expensive"))
  (("えん") . ("yen"))
  (("たかい") . ("expensive" "high"))
  (("いらっしゃいませ") . ("welcome" "welcome to our store"))
  (("(~を)おねがいします") . ("please"))
  (("(~を)ください") . ("please give me" "I'd like"))
  (("どうぞ") . ("please" "here it is" "here you go"))
  (("どうも") . ("thank you")))

(define-dictionary genki-3
  (("えいご") . ("movie"))
  (("おんがく") . ("music"))
  (("ざっし") . ("magazine"))
  (("スポーツ") . ("sports"))
  (("デート") . ("date"))
  (("テニス") . ("tennis"))
  (("テレビ") . ("TV"))
  (("アイスクリーム") . ("ice cream" "ais krom"))
  (("あさごはん") . ("breakfast"))
  (("おさけ") . ("sake" "alcohol"))
  (("おちゃ") . ("tea" "green tea"))
  (("コーヒー") . ("coffee"))
  (("ばんほはん") . ("dinner"))
  (("ハンバーガー") . ("hamburger"))
  (("ひろごはん") . ("lunch"))
  (("みず") . ("water"))
  (("いえ") . ("home" "house"))
  (("うち") . ("home" "house" "my place"))
  (("がっこう") . ("school"))
  (("あさ") . ("morning"))
  (("あした") . ("tomorrow"))
  (("いつ") . ("when"))
  (("きょう") . ("today"))
  (("~ごろ") . ("at about"))
  (("こんばん") . ("tonight"))
  (("しゅうまつ") . ("weekend"))
  (("どようび") . ("Saturday"))
  (("いちようび") . ("Sunday"))
  (("まいにち") . ("every day"))
  (("まいばん") . ("every night"))
  (("いく") . ("to go"))
  (("かえる") . ("to go back" "to return"))
  (("きく") . ("to listen" "to hear"))
  (("のむ") . ("to drink"))
  (("はなす") . ("to speak" "to talk"))
  (("よむ") . ("to read"))
  (("おきる") . ("to get up"))
  (("たべる") . ("to eat"))
  (("ねる") . ("to sleep" "to go to sleep"))
  (("みる") . ("to see" "to look at" "to watch"))
  (("くる") . ("to come"))
  (("する") . ("to do"))
  (("べんきょう") . ("to study"))
  (("いい") . ("good"))
  (("はやい") . ("early"))
  (("あまり (+neg)") . ("not much"))
  (("ぜんぜん (+neg)") . ("not at all"))
  (("たいてい") . ("usually"))
  (("ちょっと") . ("a little" "a bit"))
  (("ときどき") . ("sometimes"))
  (("よく") . ("often" "much"))
  (("どうですか") . ("how about" "how is")))
