#|
 This file is a part of Trainer
 (c) 2013 TymoonNET/NexT http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.tymoonnext.colleen.mod.trainer)

(define-dictionary genki-1
  (("いま") . ("now"))
  (("えいご") . ("english"))
  (("ええ") . ("yes"))
  (("がくせい") . ("student"))
  (("~ご") . ("language"))
  (("こうこう") . ("high school"))
  (("ごご") . ("pm"))
  (("ごぜん") . ("am"))
  (("~さい") . ("years old"))
  (("~さん") . ("mr" "ms" "mr/ms"))
  (("~さい") . ("years old"))
  (("~じ") . ("o'clock" "o clock"))
  (("~じん") . ("people"))
  (("せんこう") . ("major"))
  (("せんせい") . ("teacher" "professor"))
  (("だいがく") . ("college" "university" "uni"))
  (("でんわ") . ("telephone"))
  (("ともだち") . ("friend" "friends"))
  (("なまえ") . ("name"))
  (("なん" "なに") . ("what"))
  (("にほん") . ("japan"))
  (("~ねんせい") . ("year student" "grade student"))
  (("はい") . ("yes"))
  (("はん") . ("half"))
  (("ばんごう") . ("number"))
  (("りゅうがくせい") . ("international student"))
  (("わたし") . ("I"))
  (("アメリカ") . ("amerika"))
  (("イギリス") . ("england"))
  (("オーストラリア") . ("australia"))
  (("かんこく") . ("korea"))
  (("スウエーデン") . ("sweden"))
  (("ちゅうごく") . ("china"))
  (("かがく") . ("science"))
  (("アジアけんきゅう") . ("asian studies"))
  (("けいざい") . ("economics"))
  (("こくさいかんけい") . ("international relations"))
  (("コンピューター") . ("computer"))
  (("じんるいがく") . ("anthropology"))
  (("せいじ") . ("politics"))
  (("ビジネス") . ("business"))
  (("ぶんがく") . ("literature"))
  (("れきし") . ("history"))
  (("しごと") . ("job" "work" "occupation"))
  (("いしゃ") . ("doctor"))
  (("かいしゃいん") . ("office worker"))
  (("こうこうせい") . ("high school student"))
  (("しゅふ") . ("house wife" "housewife"))
  (("だいがくいんせい") . ("graduate student"))
  (("だいがくせい") . ("college student"))
  (("べんごし") . ("lawyer"))
  (("おかあさん") . ("mother"))
  (("おとうさん") . ("father"))
  (("おねえさん") . ("older sister"))
  (("おにいさん") . ("older brother"))
  (("いもうと") . ("younger sister"))
  (("おとうと") . ("younger brother")))

(define-dictionary genki-2
  (("これ") . ("this one"))
  (("それ") . ("that one"))
  (("あれ") . ("that one" "that one over there"))
  (("どれ") . ("which one"))
  (("この") . ("this"))
  (("その") . ("that"))
  (("あの") . ("that" "that over there"))
  (("どの") . ("which"))
  (("ここ") . ("here"))
  (("そこ") . ("there"))
  (("あそこ") . ("there" "over there"))
  (("とこ") . ("where"))
  (("だれ") . ("who"))
  (("おいしい") . ("delicious"))
  (("さかな") . ("fish"))
  (("とんかつ") . ("pork cutlet" "pork"))
  (("にく") . ("meat"))
  (("メニュウ") . ("menu"))
  (("やさい") . ("vegetable"))
  (("えんぴつ") . ("pencil"))
  (("かさ") . ("umbrella"))
  (("かばん") . ("bag"))
  (("くつ") . ("shoes"))
  (("さいふ") . ("wallet"))
  (("ジーンス") . ("jeans"))
  (("じしょ") . ("dictionary"))
  (("じてんしゃ") . ("bicycle"))
  (("しんぶん") . ("newspaper"))
  (("Ｔシャツ") . ("tshirt" "t shirt"))
  (("とけい") . ("watch"))
  (("ノート") . ("notebook"))
  (("ペン") . ("pen"))
  (("ぼうし") . ("hat" "cap"))
  (("ほん") . ("book"))
  (("きっさてん") . ("cafe"))
  (("ぎんこう") . ("bank"))
  (("トイレ") . ("toilet"))
  (("としょかん") . ("library"))
  (("ゆうびんきゃく") . ("post office" "post"))
  (("アメリカ") . ("amerika"))
  (("イギリス") . ("england"))
  (("かんこく") . ("korea"))
  (("ちゅうごく") . ("china"))
  (("けいざい") . ("economics"))
  (("コンピューター") . ("computer"))
  (("ビジネス") . ("business"))
  (("れきし") . ("history"))
  (("おかあさん") . ("mother"))
  (("おとうさん") . ("father"))
  (("いくら") . ("how much" "how much does it cost" "how expensive"))
  (("えん") . ("yen"))
  (("たかい") . ("expensive" "high"))
  (("いらっしゃいませ") . ("welcome" "welcome to our store"))
  (("(~を)おねがいします") . ("please"))
  (("(~を)ください") . ("please give me" "I'd like"))
  (("どうぞ") . ("please" "here it is" "here you go"))
  (("どうも") . ("thank you")))

(define-dictionary genki-3
  (("えいご") . ("movie"))
  (("おんがく") . ("music"))
  (("ざっし") . ("magazine"))
  (("スポーツ") . ("sports"))
  (("デート") . ("date"))
  (("テニス") . ("tennis"))
  (("テレビ") . ("TV"))
  (("アイスクリーム") . ("ice cream" "ais krom"))
  (("あさごはん") . ("breakfast"))
  (("おさけ") . ("sake" "alcohol"))
  (("おちゃ") . ("tea" "green tea"))
  (("コーヒー") . ("coffee"))
  (("ばんほはん") . ("dinner"))
  (("ハンバーガー") . ("hamburger"))
  (("ひろごはん") . ("lunch"))
  (("みず") . ("water"))
  (("いえ") . ("home" "house"))
  (("うち") . ("home" "house" "my place"))
  (("がっこう") . ("school"))
  (("あさ") . ("morning"))
  (("あした") . ("tomorrow"))
  (("いつ") . ("when"))
  (("きょう") . ("today"))
  (("~ごろ") . ("at about"))
  (("こんばん") . ("tonight"))
  (("しゅうまつ") . ("weekend"))
  (("どようび") . ("Saturday"))
  (("いちようび") . ("Sunday"))
  (("まいにち") . ("every day"))
  (("まいばん") . ("every night"))
  (("いく") . ("to go"))
  (("かえる") . ("to go back" "to return"))
  (("きく") . ("to listen" "to hear"))
  (("のむ") . ("to drink"))
  (("はなす") . ("to speak" "to talk"))
  (("よむ") . ("to read"))
  (("おきる") . ("to get up"))
  (("たべる") . ("to eat"))
  (("ねる") . ("to sleep" "to go to sleep"))
  (("みる") . ("to see" "to look at" "to watch"))
  (("くる") . ("to come"))
  (("する") . ("to do"))
  (("べんきょう") . ("to study"))
  (("いい") . ("good"))
  (("はやい") . ("early"))
  (("あまり (+neg)") . ("not much"))
  (("ぜんぜん (+neg)") . ("not at all"))
  (("たいてい") . ("usually"))
  (("ちょっと") . ("a little" "a bit"))
  (("ときどき") . ("sometimes"))
  (("よく") . ("often" "much"))
  (("どうですか") . ("how about" "how is")))

(define-dictionary genki-4
  (("アルベイト") . ("part-time job"))
  (("かいもの") . ("shopping"))
  (("クラス") . ("klass"))
  (("あなた") . ("you" "youuuuuuuu"))
  (("いす") . ("chair"))
  (("いぬ") . ("dog" "doge" "bad dog" "no" "stop it"))
  (("おみやげ") . ("souvenir"))
  (("こども") . ("child" "welcome to the real world jackass"))
  (("ごはん") . ("rice" "meal"))
  (("しゃしん") . ("picture" "photo" "photograph"))
  (("つくえ") . ("desk"))
  (("てがみ") . ("letter"))
  (("ねこ") . ("cat"))
  (("パン") . ("bread"))
  (("ひと") . ("person"))
  (("メール") . ("e mail"))
  (("おてら") . ("temple"))
  (("こうえん") . ("park"))
  (("スーパー") . ("supermarket" "super market"))
  (("デパート") . ("department store"))
  (("バスてい") . ("bus stop"))
  (("びょういん") . ("hospital"))
  (("ホテル") . ("hotel"))
  (("ほにや") . ("book store"))
  (("まち") . ("town" "city"))
  (("レストラン") . ("restaurant"))
  (("きのう") . ("yesterday"))
  (("じかん") . ("hours"))
  (("いちじかん") . ("one hour"))
  (("てんしゅう") . ("last week"))
  (("とき") . ("when" "at the time of"))
  (("げつようび") . ("Monday"))
  (("かようび") . ("Tuesday"))
  (("すいようび") . ("Wednesday"))
  (("もくようび") . ("Thursday"))
  (("きんょうび") . ("Friday"))
  (("あう") . ("to meet" "to see"))
  (("ある") . ("there is"))
  (("かう") . ("to buy"))
  (("かく") . ("to write"))
  (("とる") . ("to take" "to pick up" "to earn" "to choose" "to harvest"))
  (("まつ") . ("to wait"))
  (("わかる") . ("to understand"))
  (("いる") . ("is in" "stays at"))
  (("ぐらい") . ("about" "around"))
  (("ごめんあさい") . ("I'm sorry"))
  (("だから") . ("so" "therefore"))
  (("たくさん") . ("many" "a lot" "lots"))
  (("どうして") . ("why"))
  (("ひとりで") . ("alone"))
  (("みぎ") . ("right"))
  (("ひだり") . ("left"))
  (("まえ") . ("front"))
  (("うしろ") . ("back"))
  (("なか") . ("inside" "in"))
  (("うえ") . ("on" "on top of"))
  (("した") . ("under" "underneath"))
  (("ちかく") . ("near" "nearby"))
  (("となり") . ("next" "next to"))
  (("あいだ") . ("between")))

(define-dictionary genki-5
  (("うみ") . ("sea"))
  (("きって") . ("postal stamp" "stamp" "post stamp" "postage stamp"))
  (("きっぷ") . ("ticket"))
  (("サーフィン") . ("surfing" "catching fresh waves yo"))
  (("しゅくだい") . ("homework"))
  (("たべもの") . ("food"))
  (("たんじょうび") . ("birthday"))
  (("テスト") . ("test"))
  (("てんき") . ("weather"))
  (("のみもの") . ("drink"))
  (("はがき") . ("postcard"))
  (("バス") . ("bus"))
  (("ひこうき") . ("airplane"))
  (("へや") . ("room"))
  (("ぼく") . ("I"))
  (("やすみ") . ("holiday" "day off" "absence"))
  (("りょこう") . ("travel"))
  (("あたらしい") . ("new"))
  (("あつい") . ("hot" "hot thing" "hot weather"))
  (("いそがしい") . ("busy"))
  (("おおきい") . ("big" "large"))
  (("おもしろい") . ("interesting" "funny"))
  (("かっこいい") . ("good looking"))
  (("こわい") . ("frightening"))
  (("さむい") . ("cold" "cold weather"))
  (("たのしい") . ("fun"))
  (("ちいさい") . ("small"))
  (("つまらない") . ("boring"))
  (("ふるい") . ("old" "old thing"))
  (("むずかしい") . ("difficult"))
  (("やさしい") . ("easy" "kind"))
  (("やすい") . ("inexpensive" "cheap"))
  (("きらい") . ("disgusted with" "be disgusted with" "to dislike"))
  (("きれい") . ("beautiful" "clean"))
  (("げんき") . ("healthy" "energetic"))
  (("しずか") . ("quiet"))
  (("すき") . ("fond of" "to like"))
  (("だいきらい") . ("to hate"))
  (("だいすき") . ("very fond of" "to love"))
  (("にぎやか") . ("lively"))
  (("ひま") . ("not busy" "to have a lot of free time" "to have free time"))
  (("およぐ") . ("to swim"))
  (("きく") . ("to ask"))
  (("のる") . ("to ride" "to board"))
  (("やる") . ("to do" "to perform"))
  (("でかける") . ("to go out"))
  (("いっしょに") . ("together"))
  (("すごく") . ("extremely"))
  (("それから") . ("and then"))
  (("だいじょうぶ") . ("it's okay" "it's fine" "not to worry" "everything is under control"))
  (("とても") . ("very"))
  (("どんな") . ("what kind of"))
  (("~まい") . ("counter for flat objects" "flat object counter" "flat objects"))
  (("~まで") . ("to a place" "as far as a place" "till a time" "until a time")))

(define-dictionary genki-6
  (("おかね") . ("money"))
  (("おふる") . ("bath"))
  (("かんじ") . ("kanji" "chinese character"))
  (("きょうかしょ") . ("textbook"))
  (("こんじゅう") . ("this week"))
  (("ＣＤ(シーヂィー)") . ("cd" "compact disc"))
  (("しみんびょういん") . ("municipal hospital"))
  (("シャワー") . ("shower"))
  (("つぎ") . ("next"))
  (("でんき") . ("electricity"))
  (("でんしゃ") . ("train"))
  (("にもつ") . ("luggage"))
  (("パソコン") . ("personal computer" "pc" "computer"))
  (("ページ") . ("page"))
  (("もど") . ("window"))
  (("よる") . ("night"))
  (("らいしゅう") . ("next week"))
  (("らいねん") . ("next year"))
  (("たいへん") . ("tough" "tough situation"))
  (("おそぶ") . ("to play" "to spend time pleasantly"))
  (("いそぐ") . ("to hurry"))
  (("かえす") . ("to return"))
  (("けす") . ("to turn off" "to erase"))
  (("しぬ") . ("to die"))
  (("すわる") . ("to sit down"))
  (("たつ") . ("to stand up"))
  (("たばこ") . ("tabacco" "cigar"))
  (("すう") . ("to smoke" "to inhale" "to breathe"))
  (("つかう") . ("to use"))
  (("てつだう") . ("to help"))
  (("はいる") . ("to enter"))
  (("もつ") . ("to carry" "to hold"))
  (("やすむ") . ("to be absent" "to be absent from" "to rest"))
  (("あける") . ("to open" "to open something"))
  (("おしえる") . ("to teach" "to instruct"))
  (("おりる") . ("to get off"))
  (("かりる") . ("to borrow"))
  (("しめる") . ("to close" "to close something"))
  (("あびる") . ("to bathe" "to take a shower"))
  (("つける") . ("to turn on"))
  (("でんわをかける") . ("to make a phone call" "to call"))
  (("わすれる") . ("to forget" "to leave behind"))
  (("つれてくる") . ("to bring" "to bring a person"))
  (("もってくる") . ("to bring" "to brin a thing"))
  (("おとで") . ("later on"))
  (("おそく") . ("late" "do something late"))
  (("~から") . ("because"))
  (("けっこうです") . ("that wouldn't be necessary" "that would be fine" "that's alright"))
  (("すぐ") . ("right away"))
  (("ゆっくり") . ("slowly" "leisurely" "unhurriedly" "take it easy")))
